# .travis.yml
dist: precise

language: php

php:
  - 7.3

addons:
  mariadb: 10.4

cache:
  directories:
    - node_modules
    - vendor

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE tagerlyapi;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv
  - php artisan test

script:
  - vendor/bin/phpunit

after_script:
  - CODECLIMATE_REPO_TOKEN="2c43c5f33623105349c5340f31e91eb3691395cc19d29423bfb59098ceb6f663" vendor/bin/test-reporter --stdout > codeclimate.json
  - "sh -c 'if [ \"$TRAVIS_PHP_VERSION\" != \"hhvm\" ]; then curl -X POST -d @codeclimate.json -H \"Content-Type: application/json\" -H \"User-Agent: Code Climate (PHP Test Reporter v0.1.1)\" https://codeclimate.com/test_reports  ; fi'"